[workspace]
authors = ["jmxyyy <jmxyyy03@gmail.com>"]
channels = ["conda-forge"]
name = "eecs498"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
matplotlib = ">=3.10.3,<4"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu128" }
